import Head from "next/head";
import Image from "next/image";
import Header from "../components/navs/Header";
import styles from "../styles/Home.module.css";
import { useSession, signIn, signOut } from "next-auth/react";
import MobileNav from "../components/navs/MobileNav";
import Example from "../components/uiTemplates/Popover";

export default function Home() {
  const { data: session } = useSession();

  const head = () => {
    return (
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    );
  };

  if (session) {
    return (
      <>
        {head()}
        <Header />
        Signed in as {session.user.name} <br />
        <button onClick={() => signOut()}>Sign out</button>
        <MobileNav user={session.user} />
        {/* <pre className="text-7xl">{JSON.stringify(session, null, 2)}</pre> */}
      </>
    );
  }
  return (
    <>
      {head()}
      <Header />
      Not signed in <br />
      <button onClick={() => signIn()}>Sign in</button>
    </>
  );
}
