import Head from "next/head";
import Image from "next/image";
import Header from "../components/navs/Header";
import { useSession, signIn, signOut } from "next-auth/react";
import MobileNav from "../components/navs/MobileNav";
import { PostCard } from "@/components/post/PostCard";
import { Timeline } from "@/components/users/Timeline";
import Welcome from "./welcome";
import axios from "axios";
import { useEffect, useState } from "react";
import socket from "@/utils/clientSocket";
import { Button, Modal, Text, useModal } from "@nextui-org/react";
import PostId from "./post/[postid]";
import PostPageTemplate from "@/components/post/PostPageTemplate";

export default function Home({ posts }) {
  const { data: session } = useSession();
  console.log("Session", session);

  const { setVisible, bindings } = useModal();

  const closeHandler = () => {
    setVisible(false);
    console.log("closed");
  };

  const connectSocket = (user) => {
    let connected = false;

    socket.emit("setup", user);

    socket.on("connected", () => (connected = true));
    console.log("socket===>", socket);
  };
  // const posts = JSON.parse(p);

  const head = () => {
    return (
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    );
  };

  if (session) {
    return (
      <>
        {head()}
        <div className=" flex flex-col h-screen">
          <Header />
          <main className=" flex-1">
            <Timeline posts={posts} />
          </main>
          <MobileNav user={session.user} />
        </div>
      </>
    );
  }
  return (
    <>
      {head()}
      <Welcome />
    </>
  );
}

export const getServerSideProps = async (context) => {
  console.log(process.env.NEXT_PUBLIC_URL);
  const { data } = await axios.get(`${process.env.NEXT_PUBLIC_URL}/api/posts`);

  return {
    props: {
      posts: data.posts,
    },
  };
};
